name: 'Terragrunt CI'

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  Terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform v1.2.6
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.6
        terraform_wrapper: true
      
    - name: Setup Terraform version
      run: terraform --version

    - name: Setup Terragrunt v0.38.4
      run: |
        sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.38.4/terragrunt_linux_amd64"
        sudo chmod +x /bin/terragrunt
        terragrunt -v

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Terragrunt Init
      run: terragrunt init --terragrunt-non-interactive

    - name: Terragrunt Plan
      run: terragrunt run-all plan --terragrunt-non-interactive

    - name: Terragrunt Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terragrunt run-all apply --terragrunt-non-interactive
